### ISSUE TITLE
Friendly first run

### ISSUE THREAD

**Issue by gcollazo** [jpadilla/juicebox#12]
I think we should do a few things on the default **desktop VM** to _make the first run experience better_. Here are my suggestions.
- [x] Add desktop icons for all GUI apps including Terminal.
- [x] Add a `README.html` file on the desktop with some info about the VM, what's included, how to start, where to get help or report issues.
- [x] Create `~/Code` directory. The idea here is to have a directory all instructors can suggest to users for writing workshop files.
- [x] Add a start menu. How can I find installed apps?
- [x] Replace default background image with a JuiceBox design.

**Comment by gcollazo** [comment]
Something like this

![juicebox-optimizations](https://cloud.githubusercontent.com/assets/61048/6828543/d1007016-d2e4-11e4-879e-5c8a462a80c7.png)

**Comment by jpadilla** [comment]
To change background image:

``` bash
xfconf-query \
  --channel xfce4-desktop \
  --property /backdrop/screen0/monitorVGA-0/workspace0/last-image \
  --set /home/juicebox/Pictures/background.jpg
```

**Comment by gcollazo** [comment]
![juicebox-wallpaper](https://cloud.githubusercontent.com/assets/61048/6830949/b7475414-d2f3-11e4-9fe4-cbc1d68ac3ea.png)

**Comment by jpadilla** [comment]
Success!

![screen shot 2015-03-28 at 10 31 59 am](https://cloud.githubusercontent.com/assets/83319/6881507/2d79b776-d538-11e4-853a-f4390f324042.png)

**Comment by jpadilla** [comment]
[README.html](https://github.com/jpadilla/juicebox/blob/master/assets/README.html) is currently empty.

**Comment by gcollazo** [comment]
OSOM!

**Comment by gcollazo** [comment]
I think README.html should just be a converted version of the repo's main README.md. That would mean the README.md should start friendly enough for first time users.

**Comment by jpadilla** [comment]
Will do this instead. I'll open an issue after closing this one to update the README.md

``` bash
$ curl -o README.html -H "Accept: application/vnd.github.v3.html" "https://api.github.com/repos/jpadilla/juicebox/contents/README.md"
```
