### ISSUE TITLE
Ruby missing ?

### ISSUE THREAD

**Issue by Jpadilla1** [jpadilla/juicebox#14]
![screen shot 2015-03-31 at 10 04 46 am](https://cloud.githubusercontent.com/assets/3780146/6920615/839513ce-d78d-11e4-886c-093b865fae79.png)

**Comment by jpadilla** [comment]
Currently removing default system Ruby. I guess I could leave that in, but not going to advertise it as part of the features until we actually have a recommended setup for it.

**Comment by jpadilla** [comment]
Ref https://github.com/jpadilla/juicebox/blob/master/scripts/minimize.sh#L18

**Comment by froi** [comment]
There could very well be a Python, Ruby, or Go focused version of Juicebox so I don't think it's a bad thing to remove Ruby.

**Comment by jpadilla** [comment]
@froi Maybe. Existing build has a custom build and setup for Python and Go. Decided to remove the default system Ruby because it didn't follow that customized/recommended setup that I did with the others. If there's anyone doing Ruby workshops or has a good setup I'd love to have it included as well.

**Comment by froi** [comment]
@jpadilla is the custom/recommended setup derived from somewhere or just how you like it?

Would it be a problem if I add a java.sh with an installation of Tomcat that's downloaded and installed without using apt-get? Is the recommendation to use apt-get if it's available?

**Comment by jpadilla** [comment]
@froi I guess it's how I like it, based on "experience". Not saying it's the only or best way though.

Using `apt-get` or not, I guess it depends. Some things don't have an updated official repository, so either use one that is, or just a manual installation.

Re: `java.sh` it'd be interesting to see what's the size of the final OVA with that.

**Comment by jpadilla** [comment]
Resolved in 839ce71f1dfaa533cd6dcdd68c50c38d3c40b4a2
