### ISSUE TITLE
New versions uploaded

### ISSUE THREAD

**Issue by gcollazo** [jpadilla/juicebox#15]
Just uploaded the latest versions to S3.

https://io-blimp-juicebox.s3.amazonaws.com/juicebox-desktop-1.1.0.box
https://io-blimp-juicebox.s3.amazonaws.com/juicebox-desktop-1.1.0.ova
https://io-blimp-juicebox.s3.amazonaws.com/juicebox-desktop-1.1.0.ova.zip

**Comment by gcollazo** [comment]
https://io-blimp-juicebox.s3.amazonaws.com/juicebox-server-1.1.0.box
https://io-blimp-juicebox.s3.amazonaws.com/juicebox-server-1.1.0.ova
https://io-blimp-juicebox.s3.amazonaws.com/juicebox-server-1.1.0.ova.zip

**Comment by gcollazo** [comment]
Estoy pensando que no necesitamos los .zip. Al final del día el ahorro en file size es minimo. ¿Que tal si los borro?

**Comment by gcollazo** [comment]
El .ova de Desktop no me está working

**Comment by jpadilla** [comment]
@gcollazo voy a download it, acabo de crear un build nuevo y me funcionó. Que exactamente no está working?

**Comment by gcollazo** [comment]
@jpadilla pues bajé el .ova de nuevo y ahora me bregó bien. Debe ser que se corrompió el download anterior q hice.
