### ISSUE TITLE
Build, Test, and Upload v1.2.0

### ISSUE THREAD

**Issue by jpadilla** [jpadilla/juicebox#16]
Latest v1.2.0 includes Ruby 2.1 with RVM.

@gcollazo whenever you can try building and checking it out. I'd love to know the resulting size on the OVA, shouldn't be that much of a difference. If everything looks good please upload.

**Comment by gcollazo** [comment]
I'm on it

**Comment by gcollazo** [comment]
Desktop:
https://io-blimp-juicebox.s3.amazonaws.com/juicebox-desktop-1.2.0.ova
https://io-blimp-juicebox.s3.amazonaws.com/juicebox-desktop-1.2.0.box

Server:
https://io-blimp-juicebox.s3.amazonaws.com/juicebox-server-1.2.0.ova
https://io-blimp-juicebox.s3.amazonaws.com/juicebox-server-1.2.0.box
