### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by jpadilla** [jpadilla/juicebox#18]
Lots of inquiries to why Python 2 over Python 3. Might just install both next to each other and provide some aliases like `mkvirtualenv2.7` and `mkvirtualenv3.3`.

If anyone has a better setup for development with both versions, ideas are welcome.

**Comment by gcollazo** [comment]
This is what I do

``` bash
function mkvirtualenv2() {
    mkvirtualenv $1 --python=/usr/local/bin/python
}

function mkvirtualenv3() {
    mkvirtualenv $1 --python=/usr/local/bin/python3
}

function mkvirtualenvpypy() {
    mkvirtualenv $1 --python=/usr/local/bin/pypy
}
```

**Comment by jpadilla** [comment]
A couple of people also suggested https://github.com/yyuu/pyenv
