### ISSUE TITLE
Fail to change software repository settings

### ISSUE THREAD

**Issue by jenux** [jpadilla/juicebox#25]
Is root have a default password, need input here for authenticate.
Thanks
![snip20150429_1](https://cloud.githubusercontent.com/assets/528137/7384056/56f31ef6-ee5d-11e4-95b9-970a297e8ede.png)

**Comment by jpadilla** [comment]
@jenux `juicebox` should work.

**Comment by jpadilla** [comment]
Confirmed it worked. Let me know.

**Comment by jenux** [comment]
It works, thanks for fast feedback.
