### ISSUE TITLE
Build and Upload v1.3.0

### ISSUE THREAD

**Issue by jpadilla** [jpadilla/juicebox#29]

**Comment by gcollazo** [comment]
https://io-blimp-juicebox.s3.amazonaws.com/juicebox-server-1.3.0.box
https://io-blimp-juicebox.s3.amazonaws.com/juicebox-server-1.3.0.ova
https://io-blimp-juicebox.s3.amazonaws.com/juicebox-desktop-1.3.0.box
https://io-blimp-juicebox.s3.amazonaws.com/juicebox-desktop-1.3.0.ova
