### ISSUE TITLE
Una sola versión

### ISSUE THREAD

**Issue by gcollazo** [jpadilla/juicebox#7]
Me gustaría saber que piensas de la posibilidad de tener un solo box en vez de dos. Pienso que esto podría ayudar a algunos users a no confundirse y bajar el box incorrecto. :confused:

Edit: si tenemos solo una versión tendría q ser la desktop.

**Comment by jpadilla** [comment]
Not completely against it. Por lo menos anunciar el desktop version y dejar el otro for "testing". Tarda mucho hacer pruebas de building + uploading el desktop version.

**Comment by gcollazo** [comment]
El server versión me parece una optimización (download time) del desktop version. Creo que como la idea de este setup es bajar la barrera de entrada para usuarios con poca o ninguna experiencia, lo mejor es eliminar la toma de decisión en cuanto a que VM bajar.

Se me ocurre que podemos resolver esto teniendo en el website un link principal y obvio para bajar la versión desktop y usa sección secundaria para "usuarios más avanzados" donde pueden escoger que bajar.

Ya que estamos en este tema creo que el website también debe incluir los pasos específicos, con screenshots (maybe screencast) para bajar e instalar Virtual Box en Windows, Linux y Mac y como bajar e importar el VM. Otra cosa también importante sería tener traducciones del website cómo mínimo en Español e Inglés.

**Comment by jpadilla** [comment]
:+1: Yeah eso suena awesome
