### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by gcollazo** [jpadilla/juicebox#9]
The goal of this project is to create a "standard" VM that all community members can use to facilitate programming training or tutorials. The second (even more important) goal is to make the process of preparing a student system as painless as possible.

To achieve this second goal we need docs, really good docs. Las night I made a simple website to exemplify what I think is the right approach. I would like this to become a starting point to start the collaboration process with other members of the community.

Please submit your comments and help us improve this.

The very cool logo I'm using was designed by @jomajoma. The name _Juice Box_ was proposed by @jpadilla and I believe he will be renaming this project soon.

![juice-box-website-preview](https://cloud.githubusercontent.com/assets/61048/6753790/ff772470-ceee-11e4-81ca-b1aa12406e35.png)

Otro estilo de heading:

![screen_shot_2015-03-20_at_11 09 51_am](https://cloud.githubusercontent.com/assets/61048/6754267/d624f716-cef1-11e4-8010-4434425eba08.png)

**Comment by gcollazo** [comment]
Si no hay objeciones o sugerencias en relación a esto, voy a empezar a crear el HTML/CSS.

**Comment by jpadilla** [comment]
:+1:

**Comment by gcollazo** [comment]
@jpadilla: acabo de subir un first draft, check it out y dame feedback: http://jpadilla.github.io/juicebox/

**Comment by jpadilla** [comment]
@gcollazo super awesome, digging it!

**Comment by froi** [comment]
@gcollazo @jpadilla: awesome designs. Me gusta mas el segundo heading, but both look great.

**Comment by jpadilla** [comment]
@gcollazo thanks again for working on this!
